---
title: "GRIM & GRIMMER"
author: "Ian Hussey"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{GRIM & GRIMMER}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include=FALSE}

# formatting options
# set default chunk options
knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

# disable scientific notation
options(scipen = 999) 

```

```{r}

library(tidyverse)
library(scrutiny)
library(rsprite2)
library(knitr)
library(kableExtra)

min_decimals <- function(x, digits = 2) {
  sprintf(paste0("%.", digits, "f"), x)
}

```

# GRIM

Note that data is hard coded into the RMarkdown file. It could also be loaded from disk, e.g., from a correctly formatted .csv file (with the headers label, mean, sd, n, and items) to a tibble via `readr::read_csv()`. Note that the columns `"mean"` and `"sd"` must be converted to character and padded with trailing zeros after load.

```{r}

# enter your data here. Here is some example data
summary_statistics <- tibble(
    label = c("age group 1", "age group 2", "age group 2"),
    # x is the mean; it can also be a percentage or another fraction
    x     = c(31.09,         20.70,         31.92),
    sd    = c(6.03,          3.40,          4.83),
    n     = c(23,            23,            29),
    # number of items in the scale use to measure this variable. For a single item measure like "what is your age?", items = 1 (the default)
    items = c(1,             1,             1)
  ) |>
  restore_zeros_df(c(x, sd))

# apply GRIM test
grim_results <- summary_statistics |>
  grim_map()

# print table
grim_results |>
  select(label, x, sd, n, consistency) |>
  knitr::kable() |>
  kableExtra::kable_classic(full_width = FALSE)

# plot
grim_results |>
  grim_plot()

```

# GRIMMER

```{r}

# apply GRIMMER test using same extracted results
summary_statistics |> 
  grimmer_map() |> 
  rename(mean = x) |>
  # print table
  knitr::kable() |>
  kableExtra::kable_classic(full_width = FALSE)

```


